// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCommand(arg1:main.Command):Promise<void>;

export function DeleteCommand(arg1:number):Promise<void>;

export function GetCommands():Promise<Array<main.Command>>;

export function Greet(arg1:string):Promise<string>;

export function ReloadCommands():Promise<void>;

export function UpdateCommand(arg1:number,arg2:main.Command):Promise<void>;
