// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCommand(arg1) {
  return window['go']['main']['App']['AddCommand'](arg1);
}

export function DeleteCommand(arg1) {
  return window['go']['main']['App']['DeleteCommand'](arg1);
}

export function GetCommands() {
  return window['go']['main']['App']['GetCommands']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReloadCommands() {
  return window['go']['main']['App']['ReloadCommands']();
}

export function UpdateCommand(arg1, arg2) {
  return window['go']['main']['App']['UpdateCommand'](arg1, arg2);
}
